# Generated by Django 5.2.7 on 2025-10-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('direction', models.CharField(choices=[('HUM', 'Гуманитарное'), ('CHEMBIO', 'Химико-биологическое'), ('IT', 'IT-направление'), ('MATH', 'Математическое')], max_length=20)),
                ('is_budget', models.BooleanField(default=True)),
                ('required_score_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('required_score_paid', models.PositiveIntegerField(blank=True, null=True)),
                ('price_rub', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='universities/')),
                ('site_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
