# Generated by Django 5.2.7 on 2025-10-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityfaculty',
            options={'verbose_name': 'Факультет / Программа', 'verbose_name_plural': 'Факультеты / Программы'},
        ),
        migrations.AlterField(
            model_name='universityfaculty',
            name='direction',
            field=models.CharField(choices=[('it', 'IT и цифровые технологии'), ('agrarian', 'Аграрное и природопользование'), ('military', 'Военное и силовое'), ('humanities', 'Гуманитарное'), ('natural_science', 'Естественно-научное'), ('engineering', 'Инженерно-технические'), ('medical', 'Медицинское и здравоохранение'), ('interdisciplinary', 'Междисциплинарные и современные направления'), ('pedagogical', 'Педагогическое'), ('art', 'Творческое и искусство'), ('physics_math', 'Физико-математическое'), ('chem_bio', 'Химико-биологическое'), ('economics', 'Экономическое и управленческое'), ('law', 'Юридическое')], max_length=50, verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='universityfaculty',
            name='is_budget',
            field=models.BooleanField(default=True, verbose_name='Есть бюджетные места'),
        ),
        migrations.AlterField(
            model_name='universityfaculty',
            name='photo',
            field=models.ImageField(upload_to='universities/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='universityfaculty',
            name='price_rub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость обучения (руб)'),
        ),
        migrations.AlterField(
            model_name='universityfaculty',
            name='required_score_budget',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный балл (бюджет)'),
        ),
        migrations.AlterField(
            model_name='universityfaculty',
            name='required_score_paid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный балл (платно)'),
        ),
        migrations.AlterField(
            model_name='universityfaculty',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='universityfaculty',
            name='site_url',
            field=models.URLField(blank=True, verbose_name='Сайт вуза'),
        ),
        migrations.AlterField(
            model_name='universityfaculty',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название вуза'),
        ),
    ]
